<?php

function zmdate($date){
$datee = $date;
$daydate = date("z",$datee);
$yeardate = date("Y",$datee);
$yeartoday = date("Y",time());
$daytommorow = date("z",time()-86400);
$daynow = date("z",time());
$chyear = date("L",time());
if(time() <= $datee+0){
$text = "только что";
}elseif(time() <= $datee+2){
$text = "1 секунду назад";
}elseif(time() <= $datee+4){
$text = "2 секунды назад";
}elseif(time() <= $datee+6){
$text = "3 секунды назад";
}elseif(time() <= $datee+8){
$text = "4 секунды назад";
}elseif(time() <= $datee+10){
$text = "5 секунд назад";
}elseif(time() <= $datee+12){
$text = "6 секунд назад";
}elseif(time() <= $datee+14){
$text = "7 секунд назад";
}elseif(time() <= $datee+16){
$text = "8 секунд назад";
}elseif(time() <= $datee+18){
$text = "9 секунд назад";
}elseif(time() <= $datee+20){
$text = "10 секунд назад";
}elseif(time() <= $datee+22){
$text = "11 секунд назад";
}elseif(time() <= $datee+24){
$text = "12 секунд назад";
}elseif(time() <= $datee+26){
$text = "13 секунд назад";
}elseif(time() <= $datee+28){
$text = "14 секунд назад";
}elseif(time() <= $datee+30){
$text = "15 секунд назад";
}elseif(time() <= $datee+32){
$text = "16 секунд назад";
}elseif(time() <= $datee+34){
$text = "17 секунд назад";
}elseif(time() <= $datee+36){
$text = "18 секунд назад";
}elseif(time() <= $datee+38){
$text = "19 секунд назад";
}elseif(time() <= $datee+40){
$text = "20 секунд назад";
}elseif(time() <= $datee+42){
    $text = "21 секунду назад";
    }elseif(time() <= $datee+44){
    $text = "22 секунды назад";
    }elseif(time() <= $datee+46){
    $text = "23 секунды назад";
    }elseif(time() <= $datee+48){
    $text = "24 секунды назад";
    }elseif(time() <= $datee+50){
    $text = "25 секунд назад";
    }elseif(time() <= $datee+52){
    $text = "26 секунд назад";
    }elseif(time() <= $datee+54){
    $text = "27 секунд назад";
    }elseif(time() <= $datee+56){
    $text = "28 секунд назад";
    }elseif(time() <= $datee+58){
    $text = "29 секунд назад";
}elseif(time() <= $datee+60){
$text = "30 секунд назад";
}elseif(time() <= $datee+62){
$text = "31 секунду назад";
}elseif(time() <= $datee+64){
$text = "32 секунды назад";
}elseif(time() <= $datee+66){
$text = "33 секунды назад";
}elseif(time() <= $datee+68){
$text = "34 секунды назад";
}elseif(time() <= $datee+70){
$text = "35 секунд назад";
}elseif(time() <= $datee+72){
$text = "36 секунд назад";
}elseif(time() <= $datee+74){
$text = "37 секунд назад";
}elseif(time() <= $datee+76){
$text = "38 секунд назад";
}elseif(time() <= $datee+78){
$text = "39 секунд назад";
}elseif(time() <= $datee+80){
$text = "40 секунд назад";
}elseif(time() <= $datee+82){
$text = "41 секунду назад";
}elseif(time() <= $datee+84){
$text = "42 секунды назад";
}elseif(time() <= $datee+86){
$text = "43 секунды назад";
}elseif(time() <= $datee+88){
$text = "44 секунды назад";
}elseif(time() <= $datee+90){
$text = "45 секунд назад";
}elseif(time() <= $datee+92){
$text = "46 секунд назад";
}elseif(time() <= $datee+94){
$text = "47 секунд назад";
}elseif(time() <= $datee+96){
$text = "48 секунд назад";
}elseif(time() <= $datee+98){
$text = "49 секунд назад";
}elseif(time() <= $datee+100){
$text = "50 секунд назад";
}elseif(time() <= $datee+102){
$text = "51 секунду назад";
}elseif(time() <= $datee+104){
$text = "52 секунды назад";
}elseif(time() <= $datee+106){
$text = "53 секунды назад";
}elseif(time() <= $datee+108){
$text = "54 секунды назад";
}elseif(time() <= $datee+110){
$text = "55 секунд назад";
}elseif(time() <= $datee+112){
$text = "56 секунд назад";
}elseif(time() <= $datee+114){
$text = "57 секунд назад";
}elseif(time() <= $datee+116){
$text = "58 секунд назад";
}elseif(time() <= $datee+118){
$text = "59 секунд назад";
}elseif(time() <= $datee+120){
$text = "минуту назад";
}elseif(time() <= $datee+180){
$text = "2 минуты назад";
}elseif(time() <= $datee+240){
$text = "3 минуты назад";
}elseif(time() <= $datee+300){
$text = "4 минуты назад";
}elseif(time() <= $datee+360){
$text = "5 минут назад";
}elseif(time() <= $datee+420){ 
$text = "6 минут назад";       
}elseif(time() <= $datee+480){ 
$text = "7 минут назад";	   
}elseif(time() <= $datee+540){
$text = "8 минут назад";
}elseif(time() <= $datee+600){
$text = "9 минут назад";
}elseif(time() <= $datee+660){
$text = "10 минут назад";
}elseif(time() <= $datee+720){
$text = "11 минут назад";
}elseif(time() <= $datee+780){
$text = "12 минут назад";
}elseif(time() <= $datee+840){
$text = "13 минут назад";
}elseif(time() <= $datee+900){
$text = "14 минут назад";
}elseif(time() <= $datee+960){
$text = "15 минут назад";
}elseif(time() <= $datee+1020){
$text = "16 минут назад";
}elseif(time() <= $datee+1080){
$text = "17 минут назад";
}elseif(time() <= $datee+1140){
$text = "18 минут назад";
}elseif(time() <= $datee+1200){
$text = "19 минут назад";
}elseif(time() <= $datee+1260){
$text = "20 минут назад";
}elseif(time() <= $datee+1320){
$text = "21 минут назад";
}elseif(time() <= $datee+1380){
$text = "22 минуты назад";
}elseif(time() <= $datee+1440){
$text = "23 минуты назад";
}elseif(time() <= $datee+1500){
$text = "24 минуты назад";
}elseif(time() <= $datee+1560){
$text = "25 минут назад";
}elseif(time() <= $datee+1620){
$text = "26 минут назад";
}elseif(time() <= $datee+1680){
$text = "27 минут назад";
}elseif(time() <= $datee+1740){
$text = "28 минут назад";
}elseif(time() <= $datee+1800){
$text = "29 минут назад";
}elseif(time() <= $datee+1860){
$text = "30 минут назад";
}elseif(time() <= $datee+1920){
$text = "31 минуту назад";
}elseif(time() <= $datee+1980){
$text = "32 минуты назад";
}elseif(time() <= $datee+2040){
$text = "33 минуты назад";
}elseif(time() <= $datee+2100){
$text = "34 минуты назад";
}elseif(time() <= $datee+2160){
$text = "35 минут назад";
}elseif(time() <= $datee+2220){
$text = "35 минут назад";
}elseif($daynow == $daydate AND $yeardate == $yeartoday){
$text = "сегодня в ".date("H:i",$datee);
}elseif ($daytommorow == $daydate AND $yeardate == $yeartoday) {
$text = "вчера в ".date("H:i",$datee);
}else{
$text = date("d F Y ",$datee).'в'.date(" H:i",$datee);
$text = str_replace("January","января",$text);
$text = str_replace("February","февраля",$text);
$text = str_replace("March","марта",$text);
$text = str_replace("April","апреля",$text);
$text = str_replace("May","мая",$text);
$text = str_replace("June","июня",$text);
$text = str_replace("July","июля",$text);
$text = str_replace("August","августа",$text);
$text = str_replace("September","сентября",$text);
$text = str_replace("October","октября",$text);
$text = str_replace("November","ноября",$text);
$text = str_replace("December","декабря",$text);
}
return $text; 
}

function zmbd($date){ 

$datee = $date;
$daydate = date("z",$datee);
$yeardate = date("Y",$datee);
$yeartoday = date("Y",time());
$daynow = date("z",time());
$chyear = date("L",time());
if(time() <= $datee+15){
$text = "только что";
}elseif(time() <= $datee+120){
$text = "минуту назад";
}elseif(time() <= $datee+180){
$text = "2 минуты назад";
}elseif(time() <= $datee+240){
$text = "3 минуты назад";
}elseif(time() <= $datee+300){
$text = "4 минуты назад";
}elseif(time() <= $datee+360){
$text = "5 минут назад";
}elseif(time() <= $datee+420){ 
$text = "6 минут назад";
}elseif(time() <= $datee+480){
$text = "7 минут назад";
}elseif(time() <= $datee+540){
$text = "8 минут назад";
}elseif(time() <= $datee+600){
$text = "9 минут назад";
}elseif(time() <= $datee+660){
$text = "10 минут назад";
}elseif(time() <= $datee+720){
$text = "11 минут назад";
}elseif(time() <= $datee+780){
$text = "12 минут назад";
}elseif(time() <= $datee+840){
$text = "13 минут назад";
}elseif(time() <= $datee+900){
$text = "14 минут назад";
}elseif(time() <= $datee+960){
$text = "15 минут назад";
}elseif(time() <= $datee+1020){
$text = "16 минут назад";
}elseif(time() <= $datee+1080){
$text = "17 минут назад";
}elseif(time() <= $datee+1140){
$text = "18 минут назад";
}elseif(time() <= $datee+1200){
$text = "19 минут назад";
}elseif(time() <= $datee+1260){
$text = "20 минут назад";
}elseif(time() <= $datee+1320){
$text = "21 минуту назад";
}elseif(time() <= $datee+1380){
$text = "22 минуты назад";
}elseif(time() <= $datee+1440){
$text = "23 минуты назад";
}elseif(time() <= $datee+1500){
$text = "24 минуты назад";
}elseif(time() <= $datee+1560){
$text = "25 минут назад";
}elseif(time() <= $datee+1620){
$text = "26 минут назад";
}elseif(time() <= $datee+1680){
$text = "27 минут назад";
}elseif(time() <= $datee+1740){
$text = "28 минут назад";
}elseif(time() <= $datee+1800){
$text = "29 минут назад";
}elseif(time() <= $datee+1860){
$text = "30 минут назад";
}elseif($daynow == $daydate AND $yeardate == $yeartoday){
$text = "сегодня в ".date("H:i",$datee);
}else{
$text = date("d F Y",$datee);
$text = str_replace("January","января",$text);
$text = str_replace("February","февраля",$text);
$text = str_replace("March","марта",$text);
$text = str_replace("April","апреля",$text);
$text = str_replace("May","мая",$text);
$text = str_replace("June","июня",$text);
$text = str_replace("July","июля",$text);
$text = str_replace("August","августа",$text);
$text = str_replace("September","сентября",$text);
$text = str_replace("October","октября",$text);
$text = str_replace("November","ноября",$text);
$text = str_replace("December","декабря",$text);
}
return $text; // 19 ноября 2002
}

function zmdateapi($date){ // дата для api
//$datee = $date - 284012334;
$datee = $date;
$text = date("d.n.Y",$datee);
return $text; // 8.10.2017
}

function zmd($date){ // дата , для блядской тусовки (сделал вова)
//$datee = $date - 284012334;
$datee = $date;
$daydate = date("z",$datee);
$daynow = date("z",time());
$chyear = date("L",time());
$daytommorow = date("z",time()-86400);
$dayyesterday = date("z",time()+86400);
if($daynow == $daydate){
$text = "сегодня в ".date("H:i",$datee);
}elseif ($daytommorow == $daydate) {
$text = "вчера в ".date("H:i",$datee);
}elseif ($dayyesterday == $daydate) {
$text = "завтра в ".date("H:i",$datee);
}else{
$text = date("d F Y ",$datee).'в'.date(" H:i",$datee);
$text = str_replace("January","января",$text);
$text = str_replace("February","февраля",$text);
$text = str_replace("March","марта",$text);
$text = str_replace("April","апреля",$text);
$text = str_replace("May","мая",$text);
$text = str_replace("June","июня",$text);
$text = str_replace("July","июля",$text);
$text = str_replace("August","августа",$text);
$text = str_replace("September","сентября",$text);
$text = str_replace("October","октября",$text);
$text = str_replace("November","ноября",$text);
$text = str_replace("December","декабря",$text);

}
return $text;
}
?>